# Generated by Django 5.2.4 on 2025-08-13 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="id_producto",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
