# Generated by Django 5.2.4 on 2025-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_producto_id_producto_producto_is_private_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
