# Generated by Django 5.2.4 on 2025-08-13 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_producto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="id_producto",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
