# Generated by Django 5.2.4 on 2025-08-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_contactdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactdata",
            old_name="contact_email",
            new_name="customer_email",
        ),
    ]
